.\" Copyright (c) 2010, Aldis Berjoza <aldis@bsdroot.lv>
.\"
.\" Redistribution and use in source and binary forms, with or without
.\" modification, are permitted provided that the following conditions are
.\" met:
.\"
.\" * Redistributions of source code must retain the above copyright
.\"   notice, this list of conditions and the following disclaimer.
.\" * Redistributions in binary form must reproduce the above
.\"   copyright notice, this list of conditions and the following disclaimer
.\"   in the documentation and/or other materials provided with the
.\"   distribution.
.\" * Neither the name of the  nor the names of its
.\"   contributors may be used to endorse or promote products derived from
.\"   this software without specific prior written permission.
.\"
.\" THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
.\" "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
.\" LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR
.\" A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT
.\" OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
.\" SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT
.\" LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
.\" DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY
.\" THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
.\" (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
.\" OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
.\"
.Dd November 24, 2010
.Dt playd 1
.Os
.\"#############################################################################
.Sh NAME
.Nm playd
.Nd Simple to use mplayer wrapper script written in sh
.\"#############################################################################
.Sh SYNOPSIS
.Nm
.Op Cm append
.Op Ar commands | files | directories | streams
.\"#############################################################################
.Sh DESCRIPTION
.Nm
is a simple mplayer wrapper script written in pure /bin/sh.  With 
.Nm
you don't need mplayer GUI, to listen to music, watch videos, stream
video/audio.
.Nm
stores its playlist is simple plain text files, containing file names with
absolute path.
.Nm
automatically creates playlist if necessary.  It is easy to integrate
.Nm
in various window managers (i.e. fvwm2, fluxbox), scripts etc.
.Pp
.Nm
is designed K.I.S.S.
.Bl -bullet
.It
Goal is to be small, fast and very easy to use.
.It
The goal is not to be as foolproof as possible.
.El
.\"#############################################################################
.Sh COMMANDS
Commands can be mixed almost in any order. There's only one limit: 
.Cm append
must be 1st argument, if specified.
.Bl -tag -width indent
.\" again {{{
.It Cm again Xo
.Xc
Play current song again.
.\" }}}
.\" append {{{
.It Cm append
Append items to default playlist. Must be first argument on command line if
used.
.\" }}}
.\" audio-delay {{{
.It Cm audio-delay Xo
.Ar value
.Op Cm absolute
.Xc
Adjust audio delay in seconds (relative by default). If
.Cm absolute
(or alias
.Cm abs
)
is set, then audio delay will be set exactly to value in seconds.
.\" }}}
.\" brightness {{{
.It Cm brightness Xo
.Ar value
.Op Cm absolute
.Xc
Adjust brightness by value (relative by default).  If 
.Cm absolute
(or alias
.Cm abs
)
key is specified, brightness will be set to absolute value. Value can be in
range -100 to 100.
.\" }}}
.\" cat {{{
.It Cm cat
This will cat playlist (similar to
.Cm list
)
.\" }}}
.\" cd {{{
.It Cm cd Xo
.Op Ar track
.Xc
Play audio CD. (Can't append to playlist)
.\" }}}
.\" cat-favourites {{{
.It Cm cat-favourites
Cat favourite song list
.Pp
Alias: 
.Cm catfav
.\" }}}
.\" cmd {{{
.It Cm cmd Xo
.Ar 'mplayer command'
.Xc
Send command to mplayer slave directly. If command contains spaces, it should
be quoted.
.Pp
.Lk http://www.mplayerhq.hu/DOCS/tech/slave.txt "Mplayer slave mode protocol"
.\" }}}
.\" contrast {{{
.It Cm contrast Xo
.Ar value
.Op Cm absolute
.Xc
Adjust contrast by value (relative by default).  If
.Cm absolute
(or alias
.Cm abs
)
key is specified, contrast will be set to absolute value. Value can be in
range -100 to 100.
.\" }}}
.\" dvd {{{
.It Cm dvd Xo
.Op Ar track
.Xc
Play video DVD. (Can't append to playlist)
.\" }}}
.\" favourite {{{
.It Cm favourite
Add current song to favourites
.Pp
Alias:
.Cm fav
.\" }}}
.\" file {{{
.It Cm file Xo
.Ar file | directory
.Xc
Play file or directory. This option is handy if you have file name that match
one of
.Nm
commands
.\" }}}
.\" filename {{{
.It Cm filename
Display current file name (with full path) that mplayer is playing.
.\" }}}
.\" gamma {{{
.It Cm gamma Xo
.Ar value
.Op Cm absolute
.Xc
Adjust gamma by value (relative by default). If
.Cm absolute
.Cm absolute
(or alias
.Cm abs
)
key is specified, gamma will be set to absolute value. Value can be in range
-100 to 100.
.\" }}}
.\" hue {{{
.It Cm hue Xo
.Ar value
.Op Cm absolute
.Xc
Adjust hue by value (relative by default).  If
.Cm absolute
(or alias
.Cm abs
)
key is specified, hue will be set to absolute value. Value can be in range
-100 to 100.
.\" }}}
.\" jump {{{
.It Cm jump Xo
.Ar song_id |
.Cm random
.Xc
Jump to song_id or
.Cm random
(alias 
.Cm rnd
)
position in playlist
.\" }}}
.\" list {{{
.It Cm list
Show default playlist.
.Pp
Alias:
.Cm ls
.\" }}}
.\" list-favourites {{{
.It Cm list-favourites
List favourite songs
.Pp
Alias:
.Cm lsfav
.\" }}}
.\" longcat {{{
.It Cm longcat
This will cat playlist (similar to
.Cm longlist
.Pp
Alias:
.Cm lcat
)
.\" }}}
.\" longlist {{{
.It Cm longlist
Show default playlist. Each item is displayed with full path.
.Pp
Alias:
.Cm llist
.\" }}}
.\" loop {{{
.It Cm loop Xo
.Ar count | random
.Xc
Loop current song count times. If no argument, given, then don't loop.
.\" }}}
.\" mute {{{
.It Cm mute
Mute mplayer slave.
.\" }}}
.\" mext {{{
.It Cm next
Play next playlist item.
.\" }}}
.\" nocheck {{{
.It Cm nocheck Xo
.Ar file
.Xc
There are some files that are reported as application/octet-stream. These can
be various types, even text files. If you can't load some files, you can try to
use this option. It won't check for file type and extension. This can be very
useful for disk images. Note, that you need to set 
.Cm nocheck
for every file you want
.Nm
to skip filetype checks.
.\" }}}
.\" pause {{{
.It Cm pause
Pause mplayer slave.
.\" }}}
.\" play {{{
.It Cm play Xo
.Ar item1
.Op Ar item2
.Ar ...
.Xc
Play items from default playlist.
.\" }}}
.\" play-favourites {{{
.It Cm play-favourites
Load favourite songs to playlist, randomize, and play.
.Pp
Alias:
.Cm playfav
.\" }}}
.\" playlist {{{
.It Cm playlist
Play default playlist. Mplayer slave will be automatically started if necessary.
.\" }}}
.\" previous {{{
.It Cm previous
Play previous playlist item.
.Pp
Alias:
.Cm prev
.\" }}}
.\" randomise {{{
.It Cm randomise
This will randomise playlist, but won't start playing it... you'll need to run 
.Nm
.Cm playlist
to load new playlist.
.Pp
Alias:
.Cm rnd
.\" }}}
.\" restart {{{
.It Cm restart Xo
.Op Cm novid
.Xc
Sometimes
.Nm
doesn't listen to your commands. Actually
.Nm
does listen,
while mplayer doesn't. So if you don't get expected behaviour from
.Nm
, please run 
.Nm 
.Cm restart
and check if everything works. Only send bug report if same problem appears
after restart. If 
.Cm novid
is set, mplayer will only output sound.
.\" }}}
.\" restore-state {{{
.It Cm restore-state
Restore previous state if possible and start playing music.
.Pp
Alias:
.Cm restore
.\" }}}
.\" rmlist {{{
.It Cm rmlist
Remove default playlist.
.\" }}}
.\" save-state {{{
.It Cm save-state
Save playd position in playlist (works well only with playlists, that contain
unique files).
Note that playd will save current state every time you call playd.
Also playd will save state when you exit playd with
.Cm stop
command
.Pp
Alias:
.Cm save
.\" }}}
.\" saturation {{{
.It Cm saturation Xo
.Ar value
.Op Cm absolute
.Xc
Adjust saturation by value (relative by default).
If 
.Cm absolute
(or alias
.Cm abs
)
key is specified, saturation will be set to absolute value.
Value can be in range -100 to 100.
.\" }}}
.\" seek {{{
.It Cm seek Xo 
.Ar value
.Op Cm absolute | Cm percent
.Xc
Seek current file to value. If 
.Cm absolute
(or alias
.Cm abs
)
is specified, seek to absolute value in seconds. If 
.Cm percent
is specified, seek to value percent. By default mplayer slave will seek
relative in seconds. You many use modifiers (multipliers) to enter value...
such as
.Cm y, M, w, d, h, m, s
[years, Months, weeks, days, hours, minutes, seconds] (in order mentioned) 
.Pp
For example: 
.Nm 
.Cm seek
.Ar -1m30s
.\" }}}
.\" sort {{{
.It Cm sort Xo
.Op Cm reverse
.Xc
Sort or reverse sort playlist (only unique items will remain).
.\" }}}
.\" start {{{
.It Cm start Xo
.Op Cm novid
.Xc
Start mplayer slave. You won't probably need to use this, because mplayer
slave is started automatically when needed. If 
.Cm novid
is set, mplayer will only output sound.
.\" }}}
.\" status {{{
.It Cm status
Check if mplayer is started in slave mode.
.\" }}}
.\" subtitles {{{
.It Cm subtitles Xo
.Ar file
.Xc
Load subtitles. This option doesn't check for filetype.
.\" }}}
.\" stop {{{
.It Cm stop
Stop mplayer slave.
.\" }}}
.\" switch-audio {{{
.It Cm switch-audio
Cycle through the available audio tracks. (for DVD)
.Pp
Alias:
.Cm sw-audio
.\" }}}
.\" switch-subtitle {{{
.It Cm switch-subtitles
Cycle through the available subtitle tracks. (for DVD)
.Pp
Alias:
.Cm sw-subs
.\" }}}
.\" volume {{{
.It Cm volume Xo
.Ar value
.Op Cm absolute
.Xc
Adjust volume by value (relative by default). If 
.Cm absolute
(or alias
.Cm abs
)
key is specified, volume will be set to absolute value. Value can be 0 - 100
.Pp
NOTE: on FreeBSD mplayer will reset volume after you seek in file. To avoid
this you should set 
.Sy hw.snd.vpc_autoreset=0
in your
.Pa /etc/sysctl.conf
under FreeBSD
.Pp
Alias:
.Cm vol
.\" }}}
.\" file | directory | stream | playlist {{{
.It Ar file | directory | stream | playlist
play file, directory, stream or playlist. Mplayer will be automatically
started in slave mode, if necessary.
.\" }}}
.El
.\"=============================================================================
.\"#############################################################################
.Sh ENVIRONMENT
.Ev PLAYD_MPLAYER_USER_OPTIONS
controls custom command line options passed to mplayer, when it's started.
.Pp
.Ev XDG_CONFIG_HOME
makes
.Nm
keep all necessary files in this directory. By default
.Pa ~/.config/
will be used
.\"#############################################################################
.Sh EXIT STATUS
.Ex -std
.\"#############################################################################
.Sh EXAMPLES
Play all media files in /my/music directory.
.Nm
will be started automatically
.Pp
.Dl playd /my/music
.Pp
While playd is playing files you want to append two more files to playlist
.Pp
.Dl playd --append /my/other/music/1.mp3 /music/3.mp3
.Pp
You like few songs a lot, and you'd like to know their playlist ID
.Pp
.Dl playd list 
.Pp
Once you figured you know song IDs, you can play them by simply running
.Pp
.Dl playd play 1 3 5
.Pp
So you figured, that you want to listen to some Latvian radio
.Pp
.Dl playd http://www.radioskonto.lv/online_radio/stereo.m3u
.Pp
Enough is enough... Turn off the player
.Pp
.Dl playd stop
.\"#############################################################################
.Sh SUPPORTED MEDIA FILE FORMATS
.Ar *.3gp ,
.Ar *.acc ,
.Ar *.aif ,
.Ar *.aifc ,
.Ar *.aiff ,
.Ar *.ape ,
.Ar *.avi ,
.Ar *.divx ,
.Ar *.dvx ,
.Ar *.flac ,
.Ar *.m4a ,
.Ar *.m4b ,
.Ar *.m4p ,
.Ar *.m4r ,
.Ar *.mid ,
.Ar *.midi ,
.Ar *.mka ,
.Ar *.mkv ,
.Ar *.mov ,
.Ar *.mp1 ,
.Ar *.mp2 ,
.Ar *.mp3 ,
.Ar *.mp4 ,
.Ar *.mpa ,
.Ar *.mpf ,
.Ar *.mpg ,
.Ar *.mpga ,
.Ar *.oga ,
.Ar *.ogg ,
.Ar *.ogm ,
.Ar *.ogv ,
.Ar *.ogx ,
.Ar *.vob ,
.Ar *.wav ,
.Ar *.wma ,
.Ar *.wmv ,
.Ar *.wv
.Pp
Basically everything supported by mplayer should be supported by playd. But
since I had to figure out file extensions myself, if some extensions are
missing, please send a bug report to
.Mt playd@bsdroot.lv
.\"#############################################################################
.Sh SUPPORTED PLAYLISTS
As of V1.7.10 playd has basic support for fallowing playlist file formats:
.Pp
.Ar *.asx ,
.Ar *.m3u ,
.Ar *.m3u8 ,
.Ar *.pls ,
.Ar *.plst ,
.Ar *.qtl ,
.Ar *.ram ,
.Ar *.wax ,
.Ar *.wpl ,
.Ar *.xspf
.Pp
NOTE: plst is simple file, with filenames/links (one per line). Sometimes,
when you want to create sample playlist for Internet steams, for example,
it is very handy to put URLs in plst.  Very simple and fast :)
.\"#############################################################################
.Sh HOMEPAGE
.Lk http://wiki.bsdroot.lv/playd "Playd wiki page"
.Lk http://hg.bsdroot.lv/pub/aldis/playd.sh "Playd Mercurial repository"
.\"#############################################################################
.Sh SEE ALSO
.Xr mplayer 1 ,
.Xr sh 1
.\"#############################################################################
.Sh AUTHORS
.An -nosplit
.An Aldis Berjoza Aq Mt playd@bsdroot.lv
.\"#############################################################################
.Sh THANKS TO
Guys at forums.freebsd.org:
.Ar DutchDaemon ,
.Ar blah ,
.Ar john_doe ,
.Ar eye
.\" vim: set ts=8 sw=8 spell spelllang=en_gb fdm=marker foldminlines=1:
